load_balancer:
  host: "0.0.0.0"
  port: "8080"

jwt:
  secret_key: "3YGFHIEUFJUHEIFJEIFJM"

servers:
  - "http://127.0.0.1:8081"
  - "http://127.0.0.1:8082"
  - "http://127.0.0.1:8083"

roles:
  admin:
    allowed_servers: ["http://127.0.0.1:8081"]
  client:
    allowed_servers: ["http://127.0.0.1:8082", "http://127.0.0.1:8083"]
  user:
    allowed_servers: ["http://127.0.0.1:8082", "http://127.0.0.1:8083"]